### ISSUE TITLE
How to use promster for prometheus in k8s?

### ISSUE THREAD

**Issue by majulong** [tdeekens/promster#326]
This is great project, I wonder how to use this for k8s? Does this have docker repo? And how to integrate to the running nodej's mircoservice? 
Thanks!

**Comment by tdeekens** [comment]
It can certainly be used in a k8s environment. We ourselves at work use it in 3-5 services. It is not meant to come as an own Docker image (at least how I see it) as it should run within your Node.JS server's process. So you would just hook it into the middleware chain. Optimally start/use the server here and expose the metrics on another port than the application. Then this metrics port is internal to the cluster so that the scraper can collect metrics while from the outside nowbody can view them. Does this make sense?

**Comment by tdeekens** [comment]
Will close this due to inactivity.
